baseURL = "https://www.dienerbrothers.de/"
languageCode = "en-us"
theme = "PaperModX"
title = "Diener Brothers"

enableRobotsTXT= true
buildDrafts= false
buildFuture= false
buildExpired= false
pygmentsUseClasses= true

timeout =  90000

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Diener Brothers"
description = "Diener Brothers GbR."
keywords = [ "Blog", "Portfolio", "Gamedev", "David Diener", "Paul Diener", "Diener Brothers"]
author = "David Diener"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false
TocSide = "left"
EnableInstantClick = true

[params.assets]
favicon = "favicon.ico" 

[params.homeInfoParams]
Title = "Hi there \U0001F44B"
Content = "We are developing a game!"

[[params.socialIcons]]
name = "twitter-simple"
url = "https://x.com/dienerbrothers"

[params.cover]
hidden = false
hiddenInList = true
hiddenInSingle = false

[[menu.main]]
name = "Archive"
url = "/archive/"
weight = 10

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 20

[markup.goldmark.renderer]
unsafe= true